import type { Product } from "@/types/product";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Laptop Lenovo ThinkPad",
    sku: "LENOVO001",
    description: "Laptop biznesowy",
    manufacturer: "Lenovo",
    category: "Elektronika",
    features: ["Bestseller"],
    netPrice: 4064.23,
    grossPrice: 4999,
    vat: 23,
    currency: "PLN",
    available: true,
    limited: true,
    stock: 12,
    minQuantity: 1,
    maxQuantity: 2,
  },
  {
    id: "2",
    name: "Monitor Dell 27",
    sku: "DELL27001",
    description: "Monitor 27 cali",
    manufacturer: "Dell",
    category: "Elektronika",
    features: ["Polecany"],
    netPrice: 1218.7,
    grossPrice: 1499,
    vat: 23,
    currency: "PLN",
    available: true,
    limited: true,
    stock: 26,
    minQuantity: 1,
    maxQuantity: 4,
  },
  {
    id: "3",
    name: "Apple Magic Mouse",
    sku: "APPLEMM01",
    description: "",
    manufacturer: "Apple",
    category: "Akcesoria",
    features: ["Nowość"],
    netPrice: 405.69,
    grossPrice: 499,
    vat: 23,
    currency: "PLN",
    available: true,
    limited: false,
    stock: null,
    minQuantity: 1,
    maxQuantity: 5,
  },
  {
    id: "4",
    name: "Sony WH1000XM5",
    sku: "SONYXM5001",
    description: "Słuchawki bezprzewodowe",
    manufacturer: "Sony",
    category: "Elektronika",
    features: ["Bestseller", "Polecany"],
    netPrice: 1299.19,
    grossPrice: 1598,
    vat: 23,
    currency: "PLN",
    available: false,
    limited: true,
    stock: 0,
    minQuantity: 1,
    maxQuantity: 2,
  },
  {
    id: "5",
    name: "Samsung Portable SSD",
    sku: "SAMSUNGSSD1",
    description: "Przenośny dysk SSD",
    manufacturer: "Samsung",
    category: "Akcesoria",
    features: ["Promocja"],
    netPrice: 568.29,
    grossPrice: 699,
    vat: 23,
    currency: "PLN",
    available: true,
    limited: true,
    stock: 18,
    minQuantity: 1,
    maxQuantity: 3,
  },
];
