import type { Product } from "@/types/product";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "1",
    name: 'MacBook Pro 14"',
    sku: "MBP14M3PRO",
    description: "Laptop Apple MacBook Pro",
    manufacturer: "Apple",
    category: "Komputery",
    features: ["WiFi", "Bluetooth", "USB-C", "Premium"],
    netPrice: 8129.27,
    grossPrice: 9999,
    vat: 23,
    currency: "PLN",
    available: true,
    limited: false,
    stock: null,
    minQuantity: 1,
    maxQuantity: 10,
  },
  {
    id: "2",
    name: "Galaxy S24 Ultra",
    sku: "SGS24U256",
    description: "Smartfon Samsung Galaxy S24 Ultra",
    manufacturer: "Samsung",
    category: "Telefony",
    features: ["WiFi", "Bluetooth", "USB-C", "Wodoodporny"],
    netPrice: 5121.14,
    grossPrice: 6299,
    vat: 23,
    currency: "PLN",
    available: true,
    limited: true,
    stock: 45,
    minQuantity: 1,
    maxQuantity: 5,
  },
  {
    id: "3",
    name: "Sony WH-1000XM5",
    sku: "SNWH1000XM5",
    description: "Słuchawki bezprzewodowe Sony",
    manufacturer: "Sony",
    category: "RTV",
    features: ["Bluetooth", "Bezprzewodowy", "Premium"],
    netPrice: 1300,
    grossPrice: 1599,
    vat: 23,
    currency: "PLN",
    available: true,
    limited: false,
    stock: null,
    minQuantity: 1,
    maxQuantity: 10,
  },
  {
    id: "4",
    name: "Bosch Serie 6 WAU28P40",
    sku: "BSWAU28P40",
    description: "Pralka Bosch Serie 6",
    manufacturer: "Bosch",
    category: "AGD",
    features: ["Ekologiczny"],
    netPrice: 2682.11,
    grossPrice: 3299,
    vat: 23,
    currency: "PLN",
    available: false,
    limited: true,
    stock: 0,
    minQuantity: 1,
    maxQuantity: 2,
  },
  {
    id: "5",
    name: "Xiaomi Smart Band 8",
    sku: "XMSB8BLK",
    description: "Opaska sportowa Xiaomi",
    manufacturer: "Xiaomi",
    category: "Akcesoria",
    features: ["Bluetooth", "Wodoodporny", "Bezprzewodowy"],
    netPrice: 145.53,
    grossPrice: 179,
    vat: 23,
    currency: "PLN",
    available: true,
    limited: false,
    stock: null,
    minQuantity: 1,
    maxQuantity: 10,
  },
  {
    id: "6",
    name: "iPad Air",
    sku: "IPADAIR256",
    description: "Tablet Apple iPad Air",
    manufacturer: "Apple",
    category: "Komputery",
    features: ["WiFi", "Bluetooth", "USB-C"],
    netPrice: 2844.72,
    grossPrice: 3499,
    vat: 23,
    currency: "PLN",
    available: true,
    limited: true,
    stock: 12,
    minQuantity: 1,
    maxQuantity: 4,
  },
  {
    id: "7",
    name: "Galaxy Watch 6",
    sku: "SGWATCH6",
    description: "Smartwatch Samsung",
    manufacturer: "Samsung",
    category: "Akcesoria",
    features: ["Bluetooth", "WiFi", "Wodoodporny"],
    netPrice: 1056.1,
    grossPrice: 1299,
    vat: 23,
    currency: "PLN",
    available: true,
    limited: true,
    stock: 8,
    minQuantity: 1,
    maxQuantity: 3,
  },
];
